#!/bin/bash
for i in {1..30}
do
  echo "stay on request"
  dbus-send --system --type=method_call --print-reply --dest=org.cacophony.ATtiny /org/cacophony/ATtiny org.cacophony.ATtiny.StayOnFor int64:1
  dbus-send --system --type=method_call --print-reply --dest=org.cacophony.modemd /org/cacophony/modemd org.cacophony.modemd.StayOn
  sleep 50s
done
echo "stay on requests stopped from timeout"
