#!/usr/bin/python3 -u

"""
3g-watchdog - monitors 3G connectivity and takes action if it's down
Copyright (C) 2018, The Cacophony Project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""


import contextlib
import subprocess
import time
import yaml

TEST_HOSTS = ["8.8.8.8", "8.8.4.4"]
TEST_INTERVAL_SECS = 5 * 60

DEVICES = [
    {'name': 'spark_3G_modem', 'netdev': 'usb0', 'vendor_product': '19d2:1405'},
    {'name': 'huawei_4G_modem', 'netdev': 'eth1', 'vendor_product': '12d1:14db'},
]

def parse_config():
    with open("/etc/cacophony/3g-watchdog.yaml", "r") as stream:
        config = yaml.safe_load(stream)
        return config


class Modem:
    def __init__(self, pin, new_hardware):
        # Late import to simplify testing on developer machines.
        from RPi import GPIO

        self.power_pin = pin
        self.new_hardware = new_hardware
        self.device_name = None

        # Init power on modem
        if self.new_hardware:
            GPIO.setwarnings(False)
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(self.power_pin, GPIO.OUT)
            self.set_power(True)
            time.sleep(TEST_INTERVAL_SECS)

        # Find what modem is being used.
        for device in DEVICES:
            exitcode = subprocess.call(
                ["lsusb", "-d", device['vendor_product']], stdout=subprocess.DEVNULL
            )
            if exitcode == 0:
                self.device_name = device['name']
                self.vendor_product = device['vendor_product']
                self.netdev = device['netdev']
                print('found device ' + self.device_name)
                break
        if not self.device_name:
            print('could not find any modem device')
            return

    def cycle_power(self):
        self.set_power(False)
        print("waiting...")
        time.sleep(5)
        self.set_power(True)

    def set_power(self, on):
        from RPi import GPIO

        print("powering modem " + "on" if on else "off")
        GPIO.output(self.power_pin, GPIO.HIGH if on else GPIO.LOW)

    def is_present(self):
        if not self.device_name:
            return False
        exitcode = subprocess.call(
            ["lsusb", "-d", self.vendor_product], stdout=subprocess.DEVNULL
        )
        return exitcode == 0

    def reset(self):
        if self.new_hardware:
            self.cycle_power()
        else:
            reboot()

def main():
    print("running")
    config = parse_config()
    new_hardware = has_new_hardware()

    with contextlib.suppress(KeyboardInterrupt):
        no_link_count = 0
        modem = Modem(config["usb_power_pin"], new_hardware)
        while running():
            if modem.is_present() and is_defroute_via_dev(modem.netdev):
                print("link is using USB modem")
                if not ping_hosts(TEST_HOSTS):
                    print("ping tests FAILED")
                    modem.reset()
                else:
                    print("ping test PASSED")
            elif modem.is_present():
                if new_hardware:
                    no_link_count += 1
                    if no_link_count >= 3:
                        print("modem detected, but no connection")
                        no_link_count = 0
                        modem.reset()
            else:
                modem = Modem(config["usb_power_pin"], new_hardware)
            time.sleep(TEST_INTERVAL_SECS)

def running():
    "This exists to support patching during tests"
    return True


def is_defroute_via_dev(netdev):
    output = subprocess.check_output(["ip", "route"], universal_newlines=True)
    search = " dev " + netdev + " "
    for line in output.splitlines():
        if line.startswith("default") and search in line:
            return True
    return False


def ping_hosts(addrs):
    # Try a number of times to allow for flaky connections. We want to
    # be really sure the link is down before taking action.
    for _ in range(5):
        for addr in addrs:
            if ping_host(addr):
                return True
    return False


def ping_host(addr):
    try:
        subprocess.check_call(
            [
                "ping",
                "-n",
                "-q",  # no DNS, quiet output
                "-c1",  # just need one response
                "-w30",  # wait up to 30s
                addr,
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return False
    return True


def has_new_hardware():
    print("checking hardware...")
    for _ in range(30):
        try:
            # For such a simple call, this is easier than depending on
            # a Python D-Bus library.
            output = subprocess.check_output(
                [
                    "dbus-send",
                    "--system",
                    "--print-reply=literal",
                    "--dest=org.cacophony.ATtiny",
                    "/org/cacophony/ATtiny",
                    "org.cacophony.ATtiny.IsPresent",
                ],
                stderr=subprocess.STDOUT,
            )
        except subprocess.CalledProcessError as err:
            last_error = err.output.decode("utf-8")
            time.sleep(10)
        else:
            return b"true" in output

    print("gave up talking to attiny-controller, assuming old hardware")
    print("last error: " + last_error)
    return False


def reboot():
    print("rebooting system")
    subprocess.check_call(["/sbin/reboot"])


if __name__ == "__main__":
    main()
