#!/bin/bash
#
# Try to load the RTC if it failed to load at boot

set -e
if [ $EUID -ne 0 ]; then
  echo "run as root"
  exit 1
fi

i=10
until /sbin/hwclock -r
do
  if [[ $i -le  0 ]]; then
    exit
  fi
  echo "failed to read RTC. Will try $i more times"
  /sbin/modprobe -r rtc_pcf8523
  /sbin/modprobe rtc_pcf8523
  ((i--))
  sleep 6s
done
echo "RTC read successful"

if timedatectl | grep -q 'NTP synchronized: yes'; then
  echo "NTP synchronized"
  /sbin/hwclock --systohc
  echo "Updated RTC"
else
  /sbin/hwclock --hctosys
  echo "NTP not synchronized. Updating time from RTC"
fi
