name: aggregate-version-info
on: [push, workflow_dispatch]
jobs:
  aggregate-version-info: # per branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - shell: bash
        run: |
          cd ./.github/workflows
          npm i
          writeout=$(node --no-warnings run.js)
          if [[ $writeout != unchanged* ]]
          then
            echo "updating readme.md"
            cd ../../
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "updated version information"
            git push
          fi