# This is a basic workflow that is manually triggered      
name: learn-github-actions
on: [workflow_dispatch]
jobs:
  aggregate-version-info: # per branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - shell: bash
        run: echo "console.log(process.env.PWD)" | node # ./.github/scripts/aggregate.js
#       - name: Upload output file
#         uses: actions/upload-artifact@v1
#         with:
#           name: output-log-file
#           path: versions.md
