name: aggregate-version-info
on: [workflow_dispatch]
jobs:
  aggregate-version-info: # per branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - shell: bash
        run: |
          npm i
          npm run aggregate